export declare enum Char {
    Dot = ".",
    Comma = ",",
    OpenPren = "(",
    ClosePren = ")",
    OpenBrace = "{",
    OpenBrack = "[",
    CloseBrace = "}",
    CloseBrack = "]",
    DoubleQuotes = "\"",
    Pipe = "|",
    Less = "<",
    Plus = "+",
    Star = "*",
    Minus = "-",
    Slash = "/",
    Equals = "=",
    Greater = ">",
    Ampersand = "&",
    Percentage = "%",
    Exclamation = "!",
    Space = " ",
    NewLine = "\n",
    Tabulation = "\t",
    CarriageReturn = "\r"
}
