export declare enum TokenType {
    If = 0,
    EOF = 1,
    Let = 2,
    Else = 3,
    Const = 4,
    While = 5,
    Comma = 6,
    String = 7,
    Equals = 8,
    ElseIf = 9,
    Return = 10,
    Number = 11,
    LoneOp = 12,
    Comment = 13,
    Function = 14,
    BinaryOp = 15,
    OpenParen = 16,
    OpenBrace = 17,
    OpenBrack = 18,
    CloseBrack = 19,
    CloseBrace = 20,
    CloseParen = 21,
    Identifier = 22,
    StatementEnd = 23
}
