export enum TokenType {
  If = 'If',
  EOF = 'EOF',
  Dot = 'Dot',
  Let = 'Let',
  Else = 'Else',
  Const = 'Const',
  While = 'While',
  Comma = 'Comma',
  Equals = 'Equals',
  ElseIf = 'ElseIf',
  Return = 'Return',
  Number = 'Number',
  LoneOp = 'LoneOp',
  String = 'String',
  Comment = 'Comment',
  Function = 'Function',
  BinaryOp = 'BinaryOp',
  Semicolon = 'Semicolon',
  OpenParen = 'OpenParen',
  OpenBrace = 'OpenBrace',
  CloseBrace = 'CloseBrace',
  CloseParen = 'CloseParen',
  Identifier = 'Identifier'
}