name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: |
        corepack enable
        pnpm install
      env:
        CI: true

    - name: Build
      run: pnpm prod